markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Sen's"
markdown: rdiscount

author: "æ™‹"
atom-baseurl: "http://shengjin.github.io"
disqus: "gopherwood"

navigations:
  - title: Blog Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Movies
    class: fa fa-film
    href: http://movie.douban.com/people/qingxiaojin/collect
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

